FROM scratch
COPY warp/.stack-work/install/x86_64-linux/lts-12.10/8.4.3/bin/http /http_warp
COPY yesod/.stack-work/install/x86_64-linux/lts-12.10/8.4.3/bin/http /http_yesod
COPY happystack/.stack-work/install/x86_64-linux/lts-12.10/8.4.3/bin/http /http_happystack
COPY scotty/.stack-work/install/x86_64-linux/lts-12.10/8.4.3/bin/http /http_scotty
COPY snap/.stack-work/install/x86_64-linux/lts-12.10/8.4.3/bin/http /http_snap
COPY spock/.stack-work/install/x86_64-linux/lts-12.10/8.4.3/bin/http /http_spock
